language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - flake8 .
script:
  - python manage.py test
notifications:
  slack: gdgmalaga:ddHhBO6Zao6SHkWXMXVSgjgJ